# ==============================================================================
# SOVEREIGN COPYRIGHT (C) 2026 KISH LATTICE 16PI INITIATIVES LLC
# SCRIPT: uhc_lattice_snap_local_v1.py
# TARGET: Ultra-High-Energy Cosmic Rays as Local Lattice Snap Events
#
# FLEET CONTEXT:
#   - uhc_lattice_probe_sim.py
#       Part 1: Simple transit (Empty Void vs Uniform 16/pi Lattice) -> FAIL
#   - uhc_lattice_gradient_sim.py
#       Part 2 (v1): Transit with shallow stiffness corridor -> FAIL
#   - uhc_lattice_gradient_v2_corridor_deep.py
#       Part 2 (v2): Transit with deep, narrow corridor -> FAIL
#
#   This script (v1: Local Snap Model):
#       Hypothesis: Amaterasu/OMG-class energies are not transported across
#       cosmological distances as conserved projectiles. Instead, they are
#       injected locally by a lattice snap (vacuum rupture) near the observer.
#
#       We model:
#         - A local snap energy reservoir (E_snap)
#         - A coupling efficiency into a single UHECR probe (eta_couple)
#         - A small local propagation loss (L_local << cosmological scale)
#       and compare the resulting arrival energy to the OMG/Amaterasu threshold.
# ==============================================================================

import numpy as np

# -----------------------------
# GLOBAL PARAMETERS (DOCUMENTED)
# -----------------------------

# Target scale: OMG / Amaterasu
E_THRESHOLD_EEV = 240.0   # EeV

# Local snap energy reservoir (in EeV equivalent)
# This is the total energy released by a lattice rupture in the local region.
E_SNAP_EEV      = 1000.0  # EeV (tunable, but explicitly declared)

# Coupling efficiency: fraction of snap energy injected into a single probe
ETA_COUPLE      = 0.30    # 30% of snap energy goes into one UHECR

# Local propagation parameters (near-Earth region)
L_LOCAL         = 0.01    # normalized local path length (<< 1.0 used in transit sims)
L_ATTENUATION   = 1.0     # same toy attenuation length as other scripts

# Optional local drag term (can be set to 0.0 to test pure injection)
K_DRAG_LOCAL    = 0.005   # small geometric drag in the local environment
KISH_STIFFNESS  = 16.0 / np.pi


def local_snap_injection(E_snap_eev, eta_couple):
    """
    Compute the initial energy of a UHECR probe generated by a local lattice snap.
    E_probe_initial = eta_couple * E_snap
    """
    return eta_couple * E_snap_eev


def propagate_local_environment(E0, L_local, n_steps=200):
    """
    Propagate the locally injected probe through a short path near the observer.
    - Baseline exponential attenuation (same form as cosmological toy model).
    - PLUS a small geometric drag term using K_DRAG_LOCAL and KISH_STIFFNESS.
    """
    x = np.linspace(0.0, L_local, n_steps)
    E = E0 * np.exp(-x / L_ATTENUATION)

    dx = L_local / (n_steps - 1)

    for i in range(1, n_steps):
        dE_drag = -K_DRAG_LOCAL * KISH_STIFFNESS * np.sqrt(max(E[i-1], 0.0)) * dx
        E[i] = max(E[i] + dE_drag, 0.0)

    return x, E


def run_uhc_lattice_snap_local_audit():
    print("[*] INITIALIZING UHECR LOCAL LATTICE SNAP AUDIT (v1)")

    # 1. Compute initial probe energy from local snap
    E_probe_initial = local_snap_injection(E_SNAP_EEV, ETA_COUPLE)

    # 2. Propagate through local environment
    x_local, E_local = propagate_local_environment(E_probe_initial, L_LOCAL)
    E_arrival = E_local[-1]

    print("\n=== LOCAL SNAP INJECTION MODEL ===")
    print(f"Snap Energy Reservoir:          {E_SNAP_EEV:8.2f} EeV")
    print(f"Coupling Efficiency (eta):      {ETA_COUPLE:8.2f}")
    print(f"Initial Probe Energy:           {E_probe_initial:8.2f} EeV")
    print(f"Arrival Energy (Local Path):    {E_arrival:8.2f} EeV")
    print("============================================")

    # 3. Threshold check (OMG / Amaterasu scale)
    print("\n=== THRESHOLD CHECK (OMG / AMATERASU SCALE) ===")
    print(f"Threshold:                      {E_THRESHOLD_EEV:.1f} EeV")
    print(f"Local Snap Model:               {'PASS' if E_arrival >= E_THRESHOLD_EEV else 'FAIL'}")
    print("============================================")

    # 4. Simple diagnostic: fractional loss over local path
    frac_loss = 1.0 - (E_arrival / E_probe_initial if E_probe_initial > 0 else 0.0)
    print("\n=== LOCAL LOSS DIAGNOSTIC ===")
    print(f"Local Path Length (normalized): {L_LOCAL:.4f}")
    print(f"Fractional Energy Loss:         {frac_loss*100.0:6.3f}%")
    print("================================")


if __name__ == '__main__':
    run_uhc_lattice_snap_local_audit()
